version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: ghcr.io/cranio-worldwide/backend:latest
    command: gunicorn cranio.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: ghcr.io/cranio-worldwide/frontend:latest
    volumes:
       - frontend_value/:/app/.next/
  nginx:
    image: nginx:1.19.3
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/cranio-worldwide.tk/fullchain.pem:/etc/nginx/certs/default.crt
      - /etc/letsencrypt/live/cranio-worldwide.tk/privkey.pem:/etc/nginx/certs/default.key
      - frontend_value:/var/html/_next/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

volumes:
  postgres_data:
  static_value:
  media_value:
  frontend_value:
