on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update server infrastructure
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: deploy
          remote_path: ~/dev
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.SSH_KEY }}
      - name: restart containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd dev/deploy
            sudo docker-compose stop
            sudo docker-compose up -d